// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.start.home;

import com.start.home.DomainModel;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect DomainModel_Roo_Configurable {
    
    declare @type: DomainModel: @Configurable;
    
}
